.PHONY: all clean show_%

# Export the location of the Python library for Cocotb
export LIBPYTHON_LOC=$(shell cocotb-config --libpython)
export PYGPI_PYTHON_BIN=$(shell which python3)

# Usage: make test_shifter
# This rule will:
# 1. Convert src/shifter.sv to build/shifter.v
# 2. Concatenate with tests/dump.v (with newline fixes)
# 3. Compile with iverilog
# 4. Run the cocotb test found in tests/test_shifter.py
test_%:
	# Ensure the build directory exists
	mkdir -p build
	
	# 1. Convert SystemVerilog to Verilog
	sv2v -w build/$*.v src/$*.sv
	
	# 2. Create the simulation wrapper with timescale and waveform dumper
	echo '`timescale 1ns/1ns' > build/$*_sim.v
	cat build/$*.v >> build/$*_sim.v
	echo "" >> build/$*_sim.v
	cat tests/dump.v >> build/$*_sim.v
	
	# 3. Compile with Icarus Verilog
	# -s $* sets your module as top, -s dump sets the dumper as top
	iverilog -o build/$*.vvp -s $* -s dump -g2012 build/$*_sim.v
	
	# 4. Run the simulation using the Cocotb VPI
	# PYTHONPATH=tests allows cocotb to find test_*.py in the tests/ folder
	PYTHONPATH=tests \
	COCOTB_TEST_MODULES=test_$* \
	TESTCASE=$(ONLY) \
	MODULE=test_$* \
	vvp -M $(shell cocotb-config --lib-dir) \
		-m $(shell cocotb-config --lib-dir)/libcocotbvpi_icarus build/$*.vvp
		
# Usage: make show_shifter
# Opens the waveform generated by the last simulation run
show_%:
	gtkwave dump.vcd

# Clean up generated files and python cache
clean:
	rm -rf build __pycache__ tests/__pycache__
	rm -f dump.vcd results.xml